<?php

namespace Yuyue8\TpWechat\template\storage;

use Yuyue8\TpWechat\service\WechatService;
use Yuyue8\TpWechat\template\BaseTemplate;

class Wechat extends BaseTemplate
{
    /**
     * 初始化
     * @param array $config
     * @return mixed|void
     */
    protected function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub
    }

    /**
     * 发送消息
     * @param string $templateId
     * @param array $data
     * @return bool|mixed
     */
    public function send(array $data = [])
    {
        /** @var WechatService $wechatService */
        $wechatService = app(WechatService::class);
        return $wechatService->sendTemplateMessage($data);
    }

    /**
     * 获取消息数据
     *
     * @param string $openid
     * @param string $tempCode
     * @param array $data
     * @param string|null $link
     * @param string|null $appid
     * @param string|null $color
     * @return array
     */
    public function getNoticeData(string $openid, string $tempCode, array $data, ?string $link = null, ?string $appid = null, ?string $color = null)
    {
        //数据组装
        $new_data = [];
        foreach ($data as $key => $val) {
            $new_data[$key]["value"] = empty($val) ? '' : $val;
            $new_data[$key]["color"] = $color != null ? $color : "#173177";
        }

        $datas = [
            'touser' => $openid,
            'data' => $new_data,
            'template_id' => $this->getTemplateCode($tempCode),
        ];

        if ($link != null && $appid != null) {
            $datas['miniprogram'] = [
                'appid' => $appid,
                'path'  => $link
            ];
        }

        return $datas;
    }
}
